/**
 * tests/converter.test.js
 *
 * Unit tests for the PerfPro .3dp parser and TCX/FIT builders.
 * Validates that parse3dp, buildTcx, and buildFit produce consistent,
 * correct output for workout time, average power, max power, speed, and distance.
 *
 * Run with: npm test
 */

import { test, describe, after } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// ── Load converter.js in a Node.js context ────────────────────────────────────
// converter.js is a browser IIFE: (function(global) { ... })(window);
// We supply a plain object as the mock `window` so it works outside a browser.
const converterSrc = readFileSync(
  join(__dirname, "..", "converter.js"),
  "utf-8"
);
const mockWindow = {};
new Function("window", converterSrc)(mockWindow);
const { parse3dp, buildTcx, buildFit, extractStartTime } =
  mockWindow.PerfProConverter;

// ── Fixture definitions ───────────────────────────────────────────────────────
const FIXTURES_DIR = join(__dirname, "fixtures");

// EXPECTED contains the locked-in baseline values for each fixture file.
// These were captured from the parser on 2026-03-12 and serve as the
// regression baseline — if any value changes, a test will fail.
//
// To update after an intentional parser change: re-run the parser against
// each fixture, verify the new values are correct, and update them here.
const EXPECTED = {
  "Over and Under variable intervals": {
    durationSec: 3570,
    avgWatts: 167,
    maxWatts: 361,
    totalDistMeters: 32196.37680053711,
  },
  "No Limits 9": {
    durationSec: 3480,
    avgWatts: 171,
    maxWatts: 425,
    totalDistMeters: 32081.695556640625,
  },
  "5x Ladder (IF=.72)": {
    durationSec: 3600,
    avgWatts: 164,
    maxWatts: 250,
    totalDistMeters: 32819.549560546875,
  },
  "No Limits 10 – Climbing v2": {
    durationSec: 3686,
    avgWatts: 185,
    maxWatts: 301,
    totalDistMeters: 28702.363967895508,
  },
  "Microburst 3": {
    durationSec: 3351,
    avgWatts: 162,
    maxWatts: 424,
    totalDistMeters: 31146.10481262207,
  },
};

const FIXTURES = [
  {
    file: "Over and Under variable intervals - #perfpro - 2026-02-18-19-01-40.3dp",
    label: "Over and Under variable intervals",
  },
  {
    file: "No Limits 9 - #perfpro - 2026-01-21-18-54-25.3dp",
    label: "No Limits 9",
  },
  {
    file: "5 x (3-1-1-30s-30s) ladder up (IF=.72) - #perfpro - 2026-01-28-19-00-11.3dp",
    label: "5x Ladder (IF=.72)",
  },
  {
    file: "No Limits 10 - Climbing v2 - #perfpro - 2026-02-04-19-05-02.3dp",
    label: "No Limits 10 – Climbing v2",
  },
  {
    file: "Microburst 3 - #perfpro - 2026-02-11-18-54-55.3dp",
    label: "Microburst 3",
  },
];

// ── TCX helpers ───────────────────────────────────────────────────────────────

/**
 * Extract the key summary metrics from a TCX string.
 * Reads from the <Lap> element and its <Extensions> block.
 */
function parseTcxStats(tcxStr) {
  const first = (tag) => {
    const m = tcxStr.match(new RegExp(`<${tag}>([^<]+)</${tag}>`));
    return m ? parseFloat(m[1]) : null;
  };
  const firstNs = (tag) => {
    const m = tcxStr.match(new RegExp(`<ns3:${tag}>([^<]+)</ns3:${tag}>`));
    return m ? parseFloat(m[1]) : null;
  };
  return {
    durationSec: first("TotalTimeSeconds"),
    distMeters: first("DistanceMeters"),
    avgWatts: firstNs("AvgWatts"),
    maxWatts: firstNs("MaxWatts"),
  };
}

// ── FIT binary helpers ────────────────────────────────────────────────────────

/**
 * Minimal FIT binary parser.
 * Scans definition and data messages and returns the lap (global 19) and
 * session (global 18) summaries, which carry duration, distance, and power.
 */
function parseFitStats(fitBytes) {
  const ab = fitBytes.buffer.slice(
    fitBytes.byteOffset,
    fitBytes.byteOffset + fitBytes.byteLength
  );
  const view = new DataView(ab);

  const u8 = (off) => view.getUint8(off);
  const u16 = (off) => view.getUint16(off, true);
  const u32 = (off) => view.getUint32(off, true);

  const defs = {}; // localType → { globalMsg, fields: [{defNum, size}] }
  const result = {};

  // FIT file layout: 14-byte header | data records | 2-byte file CRC
  let pos = 14;
  const dataEnd = fitBytes.length - 2;

  while (pos < dataEnd) {
    const hdr = u8(pos);

    // Compressed timestamp records — skip (not generated by our builder)
    if (hdr & 0x80) {
      pos++;
      continue;
    }

    const isDef = !!(hdr & 0x40);
    const localType = hdr & 0x0f;

    if (isDef) {
      // Definition message: header + reserved + arch + globalMsg(2) + fieldCount + fields
      pos++; // header byte
      pos++; // reserved
      pos++; // architecture (0 = LE)
      const globalMsg = u16(pos);
      pos += 2;
      const fieldCount = u8(pos++);

      const fields = [];
      for (let f = 0; f < fieldCount; f++) {
        const defNum = u8(pos++);
        const size = u8(pos++);
        pos++; // base type
        fields.push({ defNum, size });
      }
      defs[localType] = { globalMsg, fields };
    } else {
      // Data message
      pos++; // header byte
      const def = defs[localType];
      if (!def) break;

      const fieldData = {};
      for (const field of def.fields) {
        let val;
        if (field.size === 1) val = u8(pos);
        else if (field.size === 2) val = u16(pos);
        else if (field.size === 4) val = u32(pos);
        else val = null;
        fieldData[field.defNum] = val;
        pos += field.size;
      }

      // Lap message (global 19)
      // field 7 = total_elapsed_time (raw = seconds × 1000)
      // field 9 = total_distance (raw = meters × 100); 0xffffffff = no data
      // field 20 = avg_power (watts)
      // field 21 = max_power (watts)
      if (def.globalMsg === 19) {
        const rawDist = fieldData[9];
        result.lap = {
          durationSec:
            fieldData[7] != null ? Math.round(fieldData[7] / 1000) : null,
          distMeters:
            rawDist != null && rawDist !== 0xffffffff ? rawDist / 100 : 0,
          avgWatts: fieldData[20] ?? null,
          maxWatts: fieldData[21] ?? null,
        };
      }

      // Session message (global 18) — same field layout
      if (def.globalMsg === 18) {
        const rawDist = fieldData[9];
        result.session = {
          durationSec:
            fieldData[7] != null ? Math.round(fieldData[7] / 1000) : null,
          distMeters:
            rawDist != null && rawDist !== 0xffffffff ? rawDist / 100 : 0,
          avgWatts: fieldData[20] ?? null,
          maxWatts: fieldData[21] ?? null,
        };
      }
    }
  }

  return result;
}

// ── Formatting helpers for the report ─────────────────────────────────────────

function fmtDuration(totalSec) {
  if (totalSec == null) return "N/A";
  const h = Math.floor(totalSec / 3600);
  const m = Math.floor((totalSec % 3600) / 60);
  const s = Math.floor(totalSec % 60);
  return h > 0 ? `${h}h ${m}m ${s}s` : `${m}m ${s}s`;
}

function fmtDist(meters) {
  if (meters == null || meters === 0) return "N/A";
  const mi = (meters / 1000) * 0.621371;
  return `${meters.toFixed(0)}m (${mi.toFixed(2)} mi)`;
}

function fmtSpeed(distMeters, durationSec) {
  if (!distMeters || !durationSec) return "N/A";
  const mph = distMeters / 1609.344 / (durationSec / 3600);
  const kph = distMeters / 1000 / (durationSec / 3600);
  return `${mph.toFixed(1)} mph (${kph.toFixed(1)} km/h)`;
}

function printReport(allResults) {
  const col = (s, w = 26) => String(s ?? "N/A").padEnd(w);

  console.log(
    "\n════════════════════════════════════════════════════════════════"
  );
  console.log("  PerfPro Converter — Conversion Validation Report");
  console.log(
    "════════════════════════════════════════════════════════════════"
  );

  for (const { fixture, parsedWorkout, tcxStats, fitStats } of allResults) {
    const p = parsedWorkout.stats;
    const l = fitStats.lap ?? {};

    console.log(`\n  ┌─ ${fixture.label}`);
    console.log(
      `  │ ${"Metric".padEnd(16)} │ ${"Parsed (.3dp)".padEnd(
        26
      )} │ ${"TCX".padEnd(26)} │ FIT (lap)`
    );
    console.log(
      `  │ ${"-".repeat(16)} │ ${"-".repeat(26)} │ ${"-".repeat(
        26
      )} │ ${"-".repeat(26)}`
    );
    console.log(
      `  │ ${"Duration".padEnd(16)} │ ${col(
        fmtDuration(p.durationSec)
      )} │ ${col(fmtDuration(tcxStats.durationSec))} │ ${fmtDuration(
        l.durationSec
      )}`
    );
    console.log(
      `  │ ${"Avg Power".padEnd(16)} │ ${col(p.avgWatts + "W")} │ ${col(
        tcxStats.avgWatts != null ? tcxStats.avgWatts + "W" : "N/A"
      )} │ ${l.avgWatts != null ? l.avgWatts + "W" : "N/A"}`
    );
    console.log(
      `  │ ${"Max Power".padEnd(16)} │ ${col(p.maxWatts + "W")} │ ${col(
        tcxStats.maxWatts != null ? tcxStats.maxWatts + "W" : "N/A"
      )} │ ${l.maxWatts != null ? l.maxWatts + "W" : "N/A"}`
    );
    console.log(
      `  │ ${"Distance".padEnd(16)} │ ${col(
        fmtDist(p.totalDistMeters)
      )} │ ${col(fmtDist(tcxStats.distMeters))} │ ${fmtDist(l.distMeters)}`
    );
    console.log(
      `  │ ${"Avg Speed".padEnd(16)} │ ${col(
        fmtSpeed(p.totalDistMeters, p.durationSec)
      )} │ ${col(
        fmtSpeed(tcxStats.distMeters, tcxStats.durationSec)
      )} │ ${fmtSpeed(l.distMeters, l.durationSec)}`
    );
    console.log(`  └${"─".repeat(100)}`);
  }
}

// ── Pre-compute all conversions upfront ───────────────────────────────────────
// All conversion functions are synchronous, so we can run them at module load
// time and reference the results directly in each test — no before() needed.

const allResults = FIXTURES.map((fixture) => {
  const filePath = join(FIXTURES_DIR, fixture.file);
  const startTime =
    extractStartTime(fixture.file) ?? new Date("2026-01-01T12:00:00");

  const buf = readFileSync(filePath);
  const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
  const parsedWorkout = parse3dp(ab);
  const tcxStr = buildTcx(parsedWorkout, startTime);
  const fitBytes = buildFit(parsedWorkout, startTime);
  const tcxStats = parseTcxStats(tcxStr);
  const fitStats = parseFitStats(fitBytes);

  return { fixture, parsedWorkout, tcxStr, fitBytes, tcxStats, fitStats };
});

// ── Test suites ───────────────────────────────────────────────────────────────

for (const result of allResults) {
  const { fixture, parsedWorkout, tcxStr, fitBytes, tcxStats, fitStats } =
    result;

  describe(fixture.label, () => {
    const expected = EXPECTED[fixture.label];

    // ── Baseline regression tests ──────────────────────────────────────────
    // Assert exact values against the locked-in baseline captured 2026-03-12.
    // If any of these fail after a code change, verify the new output is
    // correct before updating the EXPECTED values above.

    test("parse3dp: duration matches baseline", () => {
      assert.strictEqual(
        parsedWorkout.stats.durationSec,
        expected.durationSec,
        `durationSec=${parsedWorkout.stats.durationSec} — expected baseline ${expected.durationSec}`
      );
    });

    test("parse3dp: avgWatts matches baseline", () => {
      assert.strictEqual(
        parsedWorkout.stats.avgWatts,
        expected.avgWatts,
        `avgWatts=${parsedWorkout.stats.avgWatts} — expected baseline ${expected.avgWatts}`
      );
    });

    test("parse3dp: maxWatts matches baseline", () => {
      assert.strictEqual(
        parsedWorkout.stats.maxWatts,
        expected.maxWatts,
        `maxWatts=${parsedWorkout.stats.maxWatts} — expected baseline ${expected.maxWatts}`
      );
    });

    test("parse3dp: totalDistMeters matches baseline", () => {
      assert.strictEqual(
        parsedWorkout.stats.totalDistMeters,
        expected.totalDistMeters,
        `totalDistMeters=${parsedWorkout.stats.totalDistMeters} — expected baseline ${expected.totalDistMeters}`
      );
    });

    // ── parse3dp structural validation ────────────────────────────────────

    test("parse3dp: athlete name is non-empty", () => {
      assert.ok(
        parsedWorkout.athleteName && parsedWorkout.athleteName.length > 0,
        "athleteName should be a non-empty string"
      );
    });

    test("parse3dp: trackpoints are in strictly ascending time order", () => {
      const tps = parsedWorkout.trackpoints;
      assert.ok(tps.length > 0, "Should have at least one trackpoint");
      for (let i = 1; i < tps.length; i++) {
        assert.ok(
          tps[i].sec > tps[i - 1].sec,
          `Trackpoint at index ${i} (sec=${tps[i].sec}) is not after index ${
            i - 1
          } (sec=${tps[i - 1].sec})`
        );
      }
    });

    test("parse3dp: no negative wattage in trackpoints", () => {
      for (const tp of parsedWorkout.trackpoints) {
        assert.ok(
          tp.watts >= 0,
          `Found negative watts (${tp.watts}) at sec=${tp.sec}`
        );
      }
    });

    // ── TCX validation ─────────────────────────────────────────────────────

    test("TCX: duration matches baseline", () => {
      assert.strictEqual(
        tcxStats.durationSec,
        expected.durationSec,
        `TCX TotalTimeSeconds=${tcxStats.durationSec} — expected baseline ${expected.durationSec}`
      );
    });

    test("TCX: avgWatts matches baseline", () => {
      assert.strictEqual(
        tcxStats.avgWatts,
        expected.avgWatts,
        `TCX AvgWatts=${tcxStats.avgWatts} — expected baseline ${expected.avgWatts}`
      );
    });

    test("TCX: maxWatts matches baseline", () => {
      assert.strictEqual(
        tcxStats.maxWatts,
        expected.maxWatts,
        `TCX MaxWatts=${tcxStats.maxWatts} — expected baseline ${expected.maxWatts}`
      );
    });

    test("TCX: distance matches baseline (within 0.1m)", () => {
      const tcxDist = tcxStats.distMeters ?? 0;
      assert.ok(
        Math.abs(tcxDist - expected.totalDistMeters) < 0.1,
        `TCX DistanceMeters=${tcxDist} — expected baseline ${expected.totalDistMeters} (diff=${Math.abs(tcxDist - expected.totalDistMeters).toFixed(4)}m)`
      );
    });

    test("TCX: well-formed XML with required elements", () => {
      assert.ok(
        tcxStr.includes("<TrainingCenterDatabase"),
        "Missing root element"
      );
      assert.ok(tcxStr.includes('Sport="Biking"'), "Missing Sport attribute");
      assert.ok(
        tcxStr.includes("<TotalTimeSeconds>"),
        "Missing TotalTimeSeconds"
      );
      assert.ok(tcxStr.includes("<Trackpoint>"), "Missing Trackpoint elements");
      assert.ok(
        tcxStr.includes("<ns3:Watts>"),
        "Missing ns3:Watts in trackpoints"
      );
    });

    // ── FIT validation ─────────────────────────────────────────────────────

    test("FIT: valid file header (.FIT magic bytes)", () => {
      assert.strictEqual(fitBytes[0], 14, "FIT header size byte should be 14");
      const magic = String.fromCharCode(
        fitBytes[8],
        fitBytes[9],
        fitBytes[10],
        fitBytes[11]
      );
      assert.strictEqual(
        magic,
        ".FIT",
        `FIT magic should be '.FIT', got '${magic}'`
      );
    });

    test("FIT: contains a lap message", () => {
      assert.ok(
        fitStats.lap,
        "FIT should contain a parsed lap message (global 19)"
      );
    });

    test("FIT: lap duration matches baseline", () => {
      assert.ok(fitStats.lap, "FIT should have a lap message");
      assert.strictEqual(
        fitStats.lap.durationSec,
        expected.durationSec,
        `FIT lap durationSec=${fitStats.lap?.durationSec} — expected baseline ${expected.durationSec}`
      );
    });

    test("FIT: lap avgWatts matches baseline", () => {
      assert.ok(fitStats.lap, "FIT should have a lap message");
      assert.strictEqual(
        fitStats.lap.avgWatts,
        expected.avgWatts,
        `FIT lap avgWatts=${fitStats.lap?.avgWatts} — expected baseline ${expected.avgWatts}`
      );
    });

    test("FIT: lap maxWatts matches baseline", () => {
      assert.ok(fitStats.lap, "FIT should have a lap message");
      assert.strictEqual(
        fitStats.lap.maxWatts,
        expected.maxWatts,
        `FIT lap maxWatts=${fitStats.lap?.maxWatts} — expected baseline ${expected.maxWatts}`
      );
    });

    test("FIT: lap distance matches baseline (within 0.01m)", () => {
      assert.ok(fitStats.lap, "FIT should have a lap message");
      const fitDist = fitStats.lap.distMeters ?? 0;
      // FIT stores distance as integer centimeters, so rounding error < 0.01m
      assert.ok(
        Math.abs(fitDist - expected.totalDistMeters) < 0.01,
        `FIT lap distMeters=${fitDist} — expected baseline ${expected.totalDistMeters} (diff=${Math.abs(fitDist - expected.totalDistMeters).toFixed(4)}m)`
      );
    });

    test("FIT: session duration matches lap duration", () => {
      assert.ok(fitStats.session, "FIT should have a session message");
      assert.strictEqual(
        fitStats.session.durationSec,
        fitStats.lap?.durationSec,
        `FIT session durationSec=${fitStats.session?.durationSec} should match lap durationSec=${fitStats.lap?.durationSec}`
      );
    });

    test("FIT: session avgWatts matches lap avgWatts", () => {
      assert.ok(fitStats.session, "FIT should have a session message");
      assert.strictEqual(
        fitStats.session.avgWatts,
        fitStats.lap?.avgWatts,
        `FIT session avgWatts=${fitStats.session?.avgWatts} should match lap avgWatts=${fitStats.lap?.avgWatts}`
      );
    });
  });
}

// ── Validation report — printed after all test output has flushed ─────────────
// after() inside a describe runs after all sibling tests complete, ensuring
// the report appears at the bottom without interfering with Node's IPC channel.

describe("Validation Report", () => {
  after(() => printReport(allResults));
  test("all fixtures processed", () =>
    assert.strictEqual(allResults.length, FIXTURES.length));
});
